name: anagram
description: A sample application
dependencies:
  browser: ^0.10.0

homepage: http://gist.github.com/Sfshaza/510f17a7d8ca0b3b05bc
gist: https://gist.github.com/Sfshaza/0532bfcb70bf5e4a900c
dartpad: https://dartpad.dartlang.org/0532bfcb70bf5e4a900c
