name: tutorialsamples
description: A sample application
environment:
  sdk: any
dependencies:
  http_server: any
  browser: any
  hop: any
  http: any
  oauth2: any
  pathos: any
  polymer: any
  args: any
transformers:
- polymer:
    entry_points:
    - web/count_down/count_down.html
    - web/its_all_about_you/index.html
    - web/slambook/slambook.html
    - web/stopwatch/index.html
