name: tutorialsamples
description: A sample application
environment:
  sdk: any
dependencies:
  http_server: any
  browser: any
  hop: any
  http: any
  oauth2: any
  pathos: any
  polymer: 0.10.0-pre.10
  args: any
transformers:
- polymer:
    entry_points:
      - web/stopwatch/index.html
