name: futures
description: A sample application

homepage: https://www.dartlang.org/docs/tutorials/futures/
gist: https://gist.github.com/Sfshaza/9e43fdcdc8848cd1490b
dartpad: https://dartpad.dartlang.org/9e43fdcdc8848cd1490b
