name: 'using_paper_elements'
description: A simple web app that uses paper elements.

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.1
  polymer: ^1.0.0-rc.2
  web_components: ^0.12.0
  reflectable: ^0.3.1

transformers:
- web_components:
    entry_points: web/index.html

environment:
  sdk: '>=1.8.3 <2.0.0'

homepage: https://www.dartlang.org/docs/tutorials/using-polymer/
