name: 'using_paper_elements'
description: A simple web app that uses paper elements.

# Uncomment the "dart_to_js_script_rewriter" lines if you are
# creating a deployment version of the app.

dependencies:
  polymer_elements: ^1.0.0-rc.1
  polymer: ^1.0.0-rc.11
  web_components: ^0.12.0
  browser: ^0.10.0
#  dart_to_js_script_rewriter: ^0.1.0+4

transformers:
- polymer:
    entry_points: web/index.html
#- dart_to_js_script_rewriter

environment:
  sdk: '>=1.8.3 <2.0.0'

homepage: https://www.dartlang.org/docs/tutorials/using-polymer/
