name: stopwatch
description: A web app that implements a stopwatch using Polymer.

dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0
  web_components: ^0.12.0
  reflectable: ^0.2.0

transformers:
- web_components:
    entry_points:
    - web/index.html
- reflectable:
    entry_points:
    - web/index.dart

environment:
  sdk: ">=1.8.3 <2.0.0"

dependency_overrides:
  polymer:
    git:
      ref: behaviors
      url: https://github.com/dart-lang/polymer-dart.git
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git

homepage: https://www.dartlang.org/docs/tutorials/creating-polymer-elements
