name: stopwatch
description: A sample application
dependencies:
  polymer: '>=0.15.1 <0.17.0'
transformers:
- polymer:
    entry_points: web/index.html

https://www.dartlang.org/docs/tutorials/polymer-intro/
