name: polymer_list
description: A simple Polymer app showing how to customize an <li> list item.

dependencies:
  polymer: ^1.0.0-rc.11
  web_components: ^0.12.0
  browser: ^0.10.0

transformers:
- polymer:
    entry_points:
    - web/index.html

environment:
  sdk: ">=1.8.3 <2.0.0"

