name: polymer_list
description: A simple Polymer app showing how to customize an <li> list item.

dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0
  web_components: ^0.12.0
  reflectable: ^0.2.0

transformers:
- web_components:
    entry_points:
    - web/index.html
- reflectable:
    entry_points:
    - web/index.dart

environment:
  sdk: ">=1.8.3 <2.0.0"

