name: slambook
description: A web/server application that gets information from a form (using Polymer) and saves it to a server.

dependencies:
  polymer: ^1.0.0-rc.11
  web_components: ^0.12.0
  browser: ^0.10.0

transformers:
- polymer:
    entry_points: web/index.html

environment:
  sdk: ">=1.8.3 <2.0.0"