name: portmanteaux_simple
description: A sample application
dependencies:
  browser: ^0.10.0

homepage: http://gist.github.com/Sfshaza/df9d4f547c5f0112a67e
gist: https://gist.github.com/Sfshaza/8640071ecb67b1309938
dartpad: https://dartpad.dartlang.org/8640071ecb67b1309938
