name: throw_error
description: A simple app that reads from a stream and throws an error when the loop iterator equals 4.
dependencies:
  args: ^0.10.0

homepage: http://gist.github.com/Sfshaza/d68171ddfdd8edeab932